# Generated by Django 2.2.14 on 2021-05-18 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cal', '0001_initial'),
        ('products', '0002_product_disable'),
        ('locations', '0002_testlocation_disable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, max_length=300, null=True)),
                ('senior_pwd_id', models.CharField(blank=True, max_length=50, null=True)),
                ('senior_pwd_file', models.FileField(blank=True, null=True, upload_to='senior_pwd_file/')),
                ('waiver', models.CharField(blank=True, max_length=50, null=True)),
                ('sick1', models.CharField(blank=True, max_length=50, null=True)),
                ('sick2', models.CharField(blank=True, max_length=50, null=True)),
                ('sick3', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified')], default='PENDING', max_length=20, null=True)),
                ('refund_discount', models.IntegerField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('', ''), ('CASH', 'Cash'), ('BANK', 'Bank'), ('PAYPAL', 'Paypal')], default='', max_length=20, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=20, null=True)),
                ('test_result_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20, null=True)),
                ('pending_test', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20, null=True)),
                ('pending_result', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20, null=True)),
                ('result_sent', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20, null=True)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='result_file/')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product')),
                ('test_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.TestLocation')),
                ('time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cal.timeChoice')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('email_corporate', 'Can Email')],
            },
        ),
        migrations.CreateModel(
            name='lab_Corporate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='result_file/')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corporate.Corporate')),
            ],
        ),
    ]
