# Generated by Django 2.2.14 on 2021-05-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporate',
            name='time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
