# Generated by Django 2.2.14 on 2021-05-18 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0002_auto_20210518_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporate',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cal.timeChoice'),
        ),
    ]
