# Generated by Django 2.2.14 on 2021-05-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0003_auto_20210518_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporate',
            name='address',
        ),
        migrations.RemoveField(
            model_name='corporate',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='corporate',
            name='sick1',
        ),
        migrations.RemoveField(
            model_name='corporate',
            name='sick2',
        ),
        migrations.RemoveField(
            model_name='corporate',
            name='sick3',
        ),
        migrations.AddField(
            model_name='corporate',
            name='admitted_facility',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='admitted_facility_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='admitted_hospital',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='admitted_hospital_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='age',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='aguesia',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='altered_mental',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='anorexia',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='anosmia',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='antecendent_cause',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='antibody',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='antibody_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='antibody_date_release',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='antibody_lab',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='antibody_result',
            field=models.CharField(blank=True, choices=[('lgM(+)lgG(-)', 'lgM(+)lgG(-)'), ('lgM(+)lgG(+)', 'lgM(+)lgG(+)'), ('lgM(-)lgG(+)', 'lgM(-)lgG(+)'), ('lgM(-)lgG(-)', 'lgM(-)lgG(-)')], default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='antigen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='antigen_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='antigen_date_release',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='antigen_lab',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='antigen_result',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('NEGATIVE', 'Negative'), ('POSITIVE', 'Positive'), ('EQUIVOCAL', 'Equivocal')], default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='asympto',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='brgy',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='cancer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='case_classification',
            field=models.CharField(blank=True, choices=[('SUSPECT', 'Suspect'), ('PROBABLE', 'Probable'), ('CONFIRMED', 'Confirmed'), ('NON-COVID-19-CASE', 'Non-Covid-19 Case')], default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='chest_ct',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='chest_ct_finding',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='chest_imaging_none',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='chest_radio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='chest_radio_finding',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='closed_setting_visit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='closed_setting_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='closed_setting_visit_details',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='como_none',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='como_others',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='consult_facility',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='coryza',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='cough',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='covid_consultation',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='covid_consultation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='cp_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='current_admitted',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='current_brgy',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='current_city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='current_cp_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='current_email',
            field=models.EmailField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='current_lot',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='current_phone_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='current_province',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='current_street',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='date_onset',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='diabetes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='diag_sari',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='diarrhea',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='discard_home',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='discarge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='dyspnea',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='facility_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='fatigue',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='fever',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='fever_temp',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='foreign_traveler',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='foreign_traveler_country',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='gastro',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='gathering_visit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='gathering_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='gathering_visit_details',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='general_weak',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='genito',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='headache',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='health_care_worker',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='health_care_worker_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='health_facility',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='health_facility_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='health_facility_visit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='health_facility_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='health_facility_visit_details',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='health_status_consult',
            field=models.CharField(blank=True, choices=[('ASYMPTOMATIC', 'Asymptomatic'), ('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('CRITICAL', 'Critical')], default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='heart_d',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='history_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='history_exposure',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('UNKNOWN', 'Unknown')], default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='history_place',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('UNKNOWN', 'Unknown')], default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='home_quarantine',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='home_quarantine_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='home_visit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='home_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='home_visit_details',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='household_contacts_name1',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='household_contacts_name2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='household_contacts_name3',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='household_contacts_name4',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='household_contacts_name5',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='household_contacts_name6',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='household_contacts_name7',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='household_contacts_name8',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='household_contacts_name9',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='household_contacts_number1',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='household_contacts_number2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='household_contacts_number3',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='household_contacts_number4',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='household_contacts_number5',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='household_contacts_number6',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='household_contacts_number7',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='household_contacts_number8',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='household_contacts_number9',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='household_contacts_setting1',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='household_contacts_setting2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='household_contacts_setting3',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='household_contacts_setting4',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='household_contacts_setting5',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='household_contacts_setting6',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='household_contacts_setting7',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='household_contacts_setting8',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='household_contacts_setting9',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='hyper',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='immediate_cause',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='int_travel_visit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='int_travel_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='int_travel_visit_details',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='live_closed',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='live_closed_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='local_stranded',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='local_stranded_city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='local_travel_visit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='local_travel_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='local_travel_visit_details',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='lot',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='lung_d',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='lung_ultra',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='lung_ultra_finding',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='market_visit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='market_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='market_visit_details',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='myalgia',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='nausea',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='neuro',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='occupation',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='ofw_city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='ofw_contact_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='ofw_country',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='ofw_employer',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='ofw_lot',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='ofw_province',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='ofw_street',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='ofw_workplace',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='other_admitted',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='other_symptoms',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='other_visit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='other_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='other_visit_details',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='philhealth',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='phone_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='pregnant',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='pregnant_lmp',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='province',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='recovered_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='region_facility',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='return_ofw',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='return_ofw_country',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='risk_pregnant',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='rt_pcr',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='rt_pcr_nps',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='rt_pcr_nps_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='rt_pcr_nps_date_release',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='rt_pcr_nps_lab',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='rt_pcr_nps_result',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('NEGATIVE', 'Negative'), ('POSITIVE', 'Positive'), ('EQUIVOCAL', 'Equivocal')], default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='rt_pcr_ops',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='rt_pcr_ops_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='rt_pcr_ops_date_release',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='rt_pcr_ops_lab',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='rt_pcr_ops_nps',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='rt_pcr_ops_nps_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='rt_pcr_ops_nps_date_release',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='rt_pcr_ops_nps_lab',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='rt_pcr_ops_nps_result',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('NEGATIVE', 'Negative'), ('POSITIVE', 'Positive'), ('EQUIVOCAL', 'Equivocal')], default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='rt_pcr_ops_result',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('NEGATIVE', 'Negative'), ('POSITIVE', 'Positive'), ('EQUIVOCAL', 'Equivocal')], default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='rt_pcr_specimen',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='rt_pcr_specimen_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='rt_pcr_specimen_date_release',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='rt_pcr_specimen_lab',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='rt_pcr_specimen_result',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('NEGATIVE', 'Negative'), ('POSITIVE', 'Positive'), ('EQUIVOCAL', 'Equivocal')], default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='school_visit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='school_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='school_visit_details',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='sore_throat',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='street',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='test_others',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='test_others_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='test_others_date_release',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='test_others_lab',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='test_others_result',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='test_positive',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='test_positive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='test_positive_lab',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='test_positive_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='transpo_visit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='transpo_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='transpo_visit_details',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='travel_history',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='travel_history_airline',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='travel_history_airline_arival',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='travel_history_airline_depart',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='travel_history_airline_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='travel_history_country',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='travel_history_local',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='travel_history_local_airline',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='travel_history_local_airline_arival',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='travel_history_local_airline_depart',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='travel_history_local_airline_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='travel_history_local_place',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='underlying_cause',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='vomiting',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='work_brgy',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='work_city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='work_contact_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='work_email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='work_lot',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='work_province',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='work_street',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='workplace',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='workplace_visit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='workplace_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='workplace_visit_details',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='corporate',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Annulled', 'Annulled'), ('Legally Separated', 'Legally Separated')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='corporate',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corporate',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='corporate',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='corporate',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='corporate',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='corporate',
            name='middle_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='corporate',
            name='nationality',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='corporate',
            name='waiver',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
