# Generated by Django 2.2.14 on 2021-05-26 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='reference_number',
        ),
    ]
