# Generated by Django 2.2.14 on 2021-05-26 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('clients', '0002_remove_client_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='reference_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Customers'),
        ),
    ]
