# Generated by Django 2.2.14 on 2021-05-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_reference_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='reference_number',
        ),
    ]
