# Generated by Django 2.2.14 on 2021-05-26 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20210526_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='reference_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Customers'),
        ),
    ]
