# Generated by Django 2.2.14 on 2021-05-26 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20210526_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='reference_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Customers'),
        ),
    ]
