# Generated by Django 2.2.14 on 2021-05-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_auto_20210526_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='rt_pcr',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
