# Generated by Django 2.2.14 on 2021-05-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_client_rt_pcr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='admitted_facility',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='admitted_hospital',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='antecendent_cause',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='antibody_lab',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='antibody_result',
            field=models.CharField(blank=True, choices=[('lgM(+)lgG(-)', 'lgM(+)lgG(-)'), ('lgM(+)lgG(+)', 'lgM(+)lgG(+)'), ('lgM(-)lgG(+)', 'lgM(-)lgG(+)'), ('lgM(-)lgG(-)', 'lgM(-)lgG(-)')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='antigen_lab',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='antigen_result',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('NEGATIVE', 'Negative'), ('POSITIVE', 'Positive'), ('EQUIVOCAL', 'Equivocal')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='brgy',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='case_classification',
            field=models.CharField(blank=True, choices=[('SUSPECT', 'Suspect'), ('PROBABLE', 'Probable'), ('CONFIRMED', 'Confirmed'), ('NON-COVID-19-CASE', 'Non-Covid-19 Case')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='chest_ct_finding',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='chest_radio_finding',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Annulled', 'Annulled'), ('Legally Separated', 'Legally Separated')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='closed_setting_visit_details',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='como_others',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='consult_facility',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='covid_consultation',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='cp_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='current_admitted',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='current_brgy',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='current_city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='current_cp_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='current_email',
            field=models.EmailField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='current_lot',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='current_phone_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='current_province',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='current_street',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='diag_sari',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='discard_home',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='facility_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='fever_temp',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='foreign_traveler',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='foreign_traveler_country',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='gathering_visit_details',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='health_care_worker',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='health_care_worker_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='health_facility',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='health_facility_visit_details',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='health_status_consult',
            field=models.CharField(blank=True, choices=[('ASYMPTOMATIC', 'Asymptomatic'), ('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('CRITICAL', 'Critical')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='history_exposure',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('UNKNOWN', 'Unknown')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='history_place',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('UNKNOWN', 'Unknown')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='home_quarantine',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='home_visit_details',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_contacts_name1',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_contacts_name2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_contacts_name3',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_contacts_name4',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_contacts_name5',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_contacts_name6',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_contacts_name7',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_contacts_name8',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_contacts_name9',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_contacts_number1',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_contacts_number2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_contacts_number3',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_contacts_number4',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_contacts_number5',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_contacts_number6',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_contacts_number7',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_contacts_number8',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_contacts_number9',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_contacts_setting1',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_contacts_setting2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_contacts_setting3',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_contacts_setting4',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_contacts_setting5',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_contacts_setting6',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_contacts_setting7',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_contacts_setting8',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='household_contacts_setting9',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='immediate_cause',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='int_travel_visit_details',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='live_closed',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='live_closed_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='local_stranded',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='local_stranded_city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='local_travel_visit_details',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='lot',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='lung_ultra_finding',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='market_visit_details',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='middle_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='nationality',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='occupation',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='ofw_city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='ofw_contact_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='ofw_country',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='ofw_employer',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='ofw_lot',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='ofw_province',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='ofw_street',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='ofw_workplace',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='other_admitted',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='other_symptoms',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='other_visit_details',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='pending_result',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='pending_test',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='philhealth',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='pregnant',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='pregnant_lmp',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='province',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='region_facility',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='result_sent',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='return_ofw',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='return_ofw_country',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='risk_pregnant',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='rt_pcr_nps_lab',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='rt_pcr_nps_result',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('NEGATIVE', 'Negative'), ('POSITIVE', 'Positive'), ('EQUIVOCAL', 'Equivocal')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='rt_pcr_ops_lab',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='rt_pcr_ops_nps_lab',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='rt_pcr_ops_nps_result',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('NEGATIVE', 'Negative'), ('POSITIVE', 'Positive'), ('EQUIVOCAL', 'Equivocal')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='rt_pcr_ops_result',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('NEGATIVE', 'Negative'), ('POSITIVE', 'Positive'), ('EQUIVOCAL', 'Equivocal')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='rt_pcr_specimen',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='rt_pcr_specimen_lab',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='rt_pcr_specimen_result',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('NEGATIVE', 'Negative'), ('POSITIVE', 'Positive'), ('EQUIVOCAL', 'Equivocal')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='school_visit_details',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='street',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='test_others_lab',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='test_others_result',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='test_positive',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='test_positive_lab',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='test_positive_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='transpo_visit_details',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='travel_history',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='travel_history_airline',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='travel_history_airline_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='travel_history_country',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='travel_history_local',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='travel_history_local_airline',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='travel_history_local_airline_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='travel_history_local_place',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='underlying_cause',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='waiver',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='work_brgy',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='work_city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='work_contact_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='work_email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='work_lot',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='work_province',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='work_street',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='workplace',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='workplace_visit_details',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
