# Generated by Django 2.2.14 on 2021-05-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_fill_onsiteclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fill_onsiteclient',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
