# Generated by Django 2.2.14 on 2021-05-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_auto_20210527_2230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fill_onSiteClient',
        ),
    ]
