# Generated by Django 3.2.6 on 2021-08-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_delete_fill_onsiteclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lab_client',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
