# Generated by Django 2.2.14 on 2021-05-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timechoice',
            options={'ordering': ['name']},
        ),
    ]
