# Generated by Django 2.2.14 on 2021-05-18 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_auto_20210518_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setmonth',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='setmonth',
            name='month_number',
        ),
    ]
