# Generated by Django 2.2.14 on 2021-05-18 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_auto_20210519_0226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setmonth',
            options={'ordering': ['-date']},
        ),
    ]
