# Generated by Django 2.2.14 on 2021-05-18 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_auto_20210519_0227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setmonth',
            options={'ordering': ['date']},
        ),
    ]
