# Generated by Django 2.2.14 on 2021-05-18 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_auto_20210519_0228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setday',
            options={'ordering': ['date']},
        ),
    ]
