# Generated by Django 2.2.14 on 2021-05-18 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_disable'),
        ('locations', '0002_testlocation_disable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('number_of_person', models.IntegerField(blank=True, null=True)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, max_length=300, null=True)),
                ('senior_pwd_id', models.CharField(blank=True, max_length=50, null=True)),
                ('senior_pwd_file', models.FileField(blank=True, null=True, upload_to='senior_pwd_file/')),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified')], default='PENDING', max_length=20)),
                ('refund_discount', models.IntegerField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('', ''), ('CASH', 'Cash'), ('BANK', 'Bank'), ('GCASH', 'GCash'), ('PAYPAL', 'Paypal')], default='', max_length=20, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=20, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product')),
                ('test_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.TestLocation')),
            ],
            options={
                'unique_together': {('email', 'reference_number')},
            },
        ),
    ]
