# Generated by Django 2.2.14 on 2021-05-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
