# Generated by Django 2.2.14 on 2021-05-18 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_disable'),
        ('locations', '0002_testlocation_disable'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('number_of_person', models.CharField(max_length=50)),
                ('day', models.DateField()),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('civil_status', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=300)),
                ('senior_pwd_id', models.CharField(blank=True, max_length=50, null=True)),
                ('senior_pwd_file', models.FileField(blank=True, null=True, upload_to='senior_pwd_file/')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product')),
                ('test_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.TestLocation')),
            ],
        ),
    ]
