# Generated by Django 2.2.14 on 2021-05-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50, verbose_name='Location Name')),
                ('location_address', models.TextField(max_length=300, verbose_name='Location Address')),
            ],
        ),
    ]
